identity: "dev.env"
logging:
  redirect: "stdout"
  level: "debug"
  output: "/tmp/syspulse_tracker.log"
  maxAge: 14
  maxSize: 10
  maxBackups: 3
restful:
  addr: "0.0.0.0:24161"
  base_path: "/api"
server:
  hub:
    host: "192.168.26.100"
    port: 24160
  restful:
    host: "localhost"
    port: 24162
    bash_path: "/callback"
heartbeat:
  host: "192.168.26.100"
  port: 24164
  bash_path: "/api"
order:
  listening_addr: ""
storage:
  file_server:
    endpoint: "192.168.26.105:9001"
    access_key: "er84iy1wjjqTCg5Fwkm9"
    secret_key: "uEoAWGTpdhcVHstDa7tVRLzx3rxWkEk2kvlgguG2"
    bucket: "syspulse"
    useSSL: false
  temp_dir: "/tmp"
monitor:
  enable: true
  frequency:
    cfg_host: "12h"
    cfg_cpu: "12h"
    cfg_interface: "12h"
    runtime: "15m"
    perf_cpu: "1m"
    perf_load: "1m"
    perf_memory: "1m"
    perf_disk: "1m"
    perf_interface: "1m"
    perf_filesystem: "30m"