identity: "dev.env"
restful:
  addr: "0.0.0.0:24161"
  base_path: "/api"
server:
  hub:
    host: "192.168.0.200"
    port: 24160
  restful:
    host: "192.168.0.200"
    port: 24162
    bash_path: "/callback"
heartbeat:
  host: "192.168.0.200"
  port: 24164
  bash_path: "/api"
order:
  listening_addr: ""
storage:
  file_server:
    endpoint: "192.168.26.105:9001"
    access_key: "g0ipu3vpDkZhTOVmIBkd"
    secret_key: "gN6o0V5sO2fzZQ1lUe2gcddM6G6sViDBUF6o9NGb"
    useSSL: false
  temp_dir: "/tmp"
monitor:
  enable: true
  frequency:
    cfg_host: 120
    cfg_cpu: 120
    cfg_interface: 120
    rt_proc: 60
    rt_net_conn: 10
    perf_cpu: 3
    perf_load: 3
    perf_memory: 3
    perf_disk: 3
    perf_interface: 3
    perf_filesystem: 120
    